# Generated by Django 5.2.1 on 2025-05-29 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id_cita', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Cita')),
                ('fecha_hora_cita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('estado', models.CharField(choices=[('Agendada', 'Agendada'), ('Confirmada', 'Confirmada'), ('Cancelada_Paciente', 'Cancelada por Paciente'), ('Cancelada_Medico', 'Cancelada por Médico'), ('Realizada', 'Realizada'), ('No_Asistio', 'No Asistió')], default='Agendada', max_length=20, verbose_name='Estado')),
                ('notas_paciente', models.TextField(blank=True, null=True, verbose_name='Notas del Paciente (ej. motivo)')),
                ('notas_adicionales_medico', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales del Médico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='AppCitasMedicas.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='AppCitasMedicas.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['fecha_hora_cita'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio_programado', models.DateTimeField(verbose_name='Fecha de Envío Programado')),
                ('medio_envio', models.CharField(choices=[('Email', 'Correo Electrónico'), ('SMS', 'SMS')], max_length=10, verbose_name='Medio de Envío')),
                ('enviado', models.BooleanField(default=False, verbose_name='¿Enviado?')),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío Real')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='AppCitasMedicas.citamedica', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
            },
        ),
        migrations.CreateModel(
            name='disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='AppCitasMedicas.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
                'unique_together': {('medico', 'fecha', 'hora_inicio')},
            },
        ),
    ]
