# Generated by Django 5.2.1 on 2025-05-30 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCitasMedicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='AppCitasMedicas.medico'),
        ),
    ]
