# Generated by Django 5.2.1 on 2025-05-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCitasMedicas', '0002_alter_disponibilidad_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Confirmada', 'Confirmada'), ('Cancelada_Paciente', 'Cancelada por Paciente'), ('Cancelada_Medico', 'Cancelada por Médico'), ('Realizada', 'Realizada'), ('No_Asistio', 'No Asistió')], default='Agendada', max_length=20, verbose_name='Estado'),
        ),
    ]
