# Generated by Django 4.2.7 on 2026-05-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCitasMedicas', '0004_alter_citamedica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Realizada', 'Realizada'), ('No_Asistio', 'No Asistió')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
