# Generated by Django 4.2.30 on 2026-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCitasMedicas', '0005_alter_citamedica_estado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['paciente', 'fecha_hora_cita'], name='AppCitasMed_pacient_39e02b_idx'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['medico', 'fecha_hora_cita'], name='AppCitasMed_medico__988677_idx'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['estado'], name='AppCitasMed_estado_a0f621_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['medico', 'fecha'], name='AppCitasMed_medico__f44375_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidad',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='AppCitasMed_fecha_cba46c_idx'),
        ),
    ]
